#Copyright (c) Chedy Missaoui All rights reserved.
#Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

# Site settings
title: Le bestiaire illustré trop bien
description: > # this means to ignore newlines until "baseurl:"
    Description du bestiaire
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: /:categories/:title.html
# Build settings
markdown: kramdown
gem:
    - html_minifier
    - uglifier
    - therubyracer
    - wdm
sass:
    style: compressed
exclude:
    - "*.bak"
    - "deploy.rb"
js_minifier:
    main: 'js/main.js'
    includes:
        - 'js/_jquery.js'
        - 'js/_bootstrap.js'
optimize_assets: false          
